"""initial schema

Revision ID: bc8d83a34fba
Revises: 
Create Date: 2026-08-26 14:06:15.943605
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bc8d83a34fba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directory_upload_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('principal_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.Enum('sdk', 'portal', name='directorysource', native_enum=False, length=16), nullable=False),
    sa.Column('root_directory_name', sa.String(length=1024), nullable=False),
    sa.Column('bucket', sa.String(length=255), nullable=False),
    sa.Column('destination_prefix', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('created', 'manifest_uploading', 'ready', 'uploading', 'paused', 'finalizing', 'completed', 'cancelling', 'cancelled', 'completed_with_errors', name='directoryjobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('conflict_policy', sa.Enum('reject', 'skip', 'overwrite', 'rename', 'compare', name='conflictpolicy', native_enum=False, length=16), nullable=False),
    sa.Column('total_entries', sa.BigInteger(), nullable=False),
    sa.Column('total_files', sa.BigInteger(), nullable=False),
    sa.Column('total_directories', sa.BigInteger(), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_files', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_bytes', sa.BigInteger(), nullable=False),
    sa.Column('failed_files', sa.BigInteger(), nullable=False),
    sa.Column('skipped_files', sa.BigInteger(), nullable=False),
    sa.Column('manifest_hash', sa.String(length=128), nullable=True),
    sa.Column('requested_lifecycle', sa.JSON(), nullable=True),
    sa.Column('effective_lifecycle', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directory_upload_jobs_status'), 'directory_upload_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_directory_upload_jobs_tenant_id'), 'directory_upload_jobs', ['tenant_id'], unique=False)
    op.create_table('file_objects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('principal_id', sa.String(length=128), nullable=False),
    sa.Column('bucket', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('storage_backend', sa.Enum('local', 's3', name='storagebackend', native_enum=False, length=16), nullable=False),
    sa.Column('original_filename', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('checksum_algorithm', sa.String(length=32), nullable=True),
    sa.Column('checksum_value', sa.String(length=128), nullable=True),
    sa.Column('file_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('upload_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('active', 'deleted', name='filestatus', native_enum=False, length=16), nullable=False),
    sa.Column('lifecycle_mode', sa.Enum('permanent', 'ttl', 'expires_at', 'temporary', 'sliding_ttl', name='lifecyclemode', native_enum=False, length=32), nullable=False),
    sa.Column('lifecycle_action', sa.Enum('delete', 'notify', 'none', name='lifecycleaction', native_enum=False, length=16), nullable=False),
    sa.Column('lifecycle_status', sa.Enum('active', 'expiring', 'expired', 'deleting', 'deleted', 'archiving', 'archived', 'restoring', name='lifecyclestatus', native_enum=False, length=32), nullable=False),
    sa.Column('ttl_seconds', sa.BigInteger(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('legal_hold', sa.Boolean(), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lifecycle_source', sa.String(length=64), nullable=False),
    sa.Column('delete_attempts', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'bucket', 'object_key', name='uq_file_objects_tenant_bucket_key')
    )
    op.create_index(op.f('ix_file_objects_next_action_at'), 'file_objects', ['next_action_at'], unique=False)
    op.create_index(op.f('ix_file_objects_tenant_id'), 'file_objects', ['tenant_id'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('operation', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=128), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'operation', 'idempotency_key', name='uq_idempotency_tenant_op_key')
    )
    op.create_index(op.f('ix_idempotency_records_expires_at'), 'idempotency_records', ['expires_at'], unique=False)
    op.create_index(op.f('ix_idempotency_records_tenant_id'), 'idempotency_records', ['tenant_id'], unique=False)
    op.create_table('lifecycle_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('directory_upload_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lifecycle_events_file_id'), 'lifecycle_events', ['file_id'], unique=False)
    op.create_index(op.f('ix_lifecycle_events_tenant_id'), 'lifecycle_events', ['tenant_id'], unique=False)
    op.create_table('upload_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('principal_id', sa.String(length=128), nullable=False),
    sa.Column('backend', sa.Enum('local', 's3', name='storagebackend', native_enum=False, length=16), nullable=False),
    sa.Column('upload_mode', sa.Enum('automatic', 'proxy', 'presigned', name='uploadmode', native_enum=False, length=16), nullable=False),
    sa.Column('bucket', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('storage_upload_id', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('total_size', sa.BigInteger(), nullable=False),
    sa.Column('part_size', sa.BigInteger(), nullable=False),
    sa.Column('total_parts', sa.Integer(), nullable=False),
    sa.Column('file_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('expected_sha256', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('initiated', 'uploading', 'completing', 'completed', 'aborting', 'aborted', 'expired', name='uploadstatus', native_enum=False, length=16), nullable=False),
    sa.Column('requested_lifecycle', sa.JSON(), nullable=True),
    sa.Column('effective_lifecycle', sa.JSON(), nullable=True),
    sa.Column('completed_file_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_sessions_status'), 'upload_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_upload_sessions_tenant_id'), 'upload_sessions', ['tenant_id'], unique=False)
    op.create_table('webhook_outbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'delivered', 'failed', name='webhookstatus', native_enum=False, length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_outbox_status'), 'webhook_outbox', ['status'], unique=False)
    op.create_index(op.f('ix_webhook_outbox_tenant_id'), 'webhook_outbox', ['tenant_id'], unique=False)
    op.create_table('directory_upload_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('directory_upload_id', sa.Uuid(), nullable=False),
    sa.Column('entry_type', sa.Enum('file', 'directory', name='entrytype', native_enum=False, length=16), nullable=False),
    sa.Column('relative_path', sa.String(length=1024), nullable=False),
    sa.Column('normalized_path', sa.String(length=1024), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('last_modified_ns', sa.BigInteger(), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('fingerprint', sa.String(length=255), nullable=True),
    sa.Column('full_sha256', sa.String(length=128), nullable=True),
    sa.Column('upload_id', sa.Uuid(), nullable=True),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'uploading', 'uploaded', 'skipped', 'failed', name='entrystatus', native_enum=False, length=16), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_lifecycle', sa.JSON(), nullable=True),
    sa.Column('effective_lifecycle', sa.JSON(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['directory_upload_id'], ['directory_upload_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('directory_upload_id', 'normalized_path', name='uq_dir_entries_job_normalized_path'),
    sa.UniqueConstraint('directory_upload_id', 'object_key', name='uq_dir_entries_job_object_key')
    )
    op.create_index(op.f('ix_directory_upload_entries_directory_upload_id'), 'directory_upload_entries', ['directory_upload_id'], unique=False)
    op.create_table('upload_parts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('part_number', sa.Integer(), nullable=False),
    sa.Column('offset_bytes', sa.BigInteger(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('pending', 'uploaded', 'committed', 'failed', name='partstatus', native_enum=False, length=16), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id', 'part_number', name='uq_upload_parts_upload_part')
    )
    op.create_index(op.f('ix_upload_parts_upload_id'), 'upload_parts', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_parts_upload_id'), table_name='upload_parts')
    op.drop_table('upload_parts')
    op.drop_index(op.f('ix_directory_upload_entries_directory_upload_id'), table_name='directory_upload_entries')
    op.drop_table('directory_upload_entries')
    op.drop_index(op.f('ix_webhook_outbox_tenant_id'), table_name='webhook_outbox')
    op.drop_index(op.f('ix_webhook_outbox_status'), table_name='webhook_outbox')
    op.drop_table('webhook_outbox')
    op.drop_index(op.f('ix_upload_sessions_tenant_id'), table_name='upload_sessions')
    op.drop_index(op.f('ix_upload_sessions_status'), table_name='upload_sessions')
    op.drop_table('upload_sessions')
    op.drop_index(op.f('ix_lifecycle_events_tenant_id'), table_name='lifecycle_events')
    op.drop_index(op.f('ix_lifecycle_events_file_id'), table_name='lifecycle_events')
    op.drop_table('lifecycle_events')
    op.drop_index(op.f('ix_idempotency_records_tenant_id'), table_name='idempotency_records')
    op.drop_index(op.f('ix_idempotency_records_expires_at'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_file_objects_tenant_id'), table_name='file_objects')
    op.drop_index(op.f('ix_file_objects_next_action_at'), table_name='file_objects')
    op.drop_table('file_objects')
    op.drop_index(op.f('ix_directory_upload_jobs_tenant_id'), table_name='directory_upload_jobs')
    op.drop_index(op.f('ix_directory_upload_jobs_status'), table_name='directory_upload_jobs')
    op.drop_table('directory_upload_jobs')
    # ### end Alembic commands ###
