apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: upload-public
  namespace: upload-service
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  rules:
    - host: upload.example.com
      http:
        paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: upload-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: upload-portal
                port:
                  number: 80
