apiVersion: v1
kind: Service
metadata:
  name: upload-api
  namespace: upload-service
spec:
  selector:
    app: upload-api
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: upload-portal
  namespace: upload-service
spec:
  selector:
    app: upload-portal
  ports:
    - port: 80
      targetPort: 80
